
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"KateUnger-copy-files","number":63,"title":"MenuItemReview Copy Backend Files - Don't Merge Yet","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/63"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization","number":62,"title":"Create fixtures for UCSBOrganization","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/62"}]
