
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-3
pull_requests: [{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-ArticlesEditPage","number":104,"title":"Added Edit Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/104"},{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-ArticlesIndexPage","number":103,"title":"Added Index Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/103"},{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-ArticlesPage","number":102,"title":"Added Create Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/102"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-DiningCommonsMenuItem-EditPage","number":100,"title":"Created Edit Page and tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/100"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-DiningCommonsMenuItem-IndexPage","number":99,"title":"Created Index page and tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/99"},{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-HelpRequestTableComponent","number":97,"title":"Added table component for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/97"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-DiningCommonsMenuItem-CreatePage","number":95,"title":"Created page for DiningCommonsMenuItems and corresponding tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/95"},{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-HelpRequestFormComponent","number":93,"title":"Added for Form Component for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/93"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization-EditPage","number":84,"title":"Create EditPage for UCSBOrganization","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/84"}]
