
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-3
pull_requests: [{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-ArticlesFixtures","number":76,"title":"Created fixtures for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/76"},{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-HelpRequestFixtures","number":75,"title":"Added fixtures to HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/75"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization-CreatePage","number":72,"title":"Create Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/72"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization-Pages","number":71,"title":"Copy Placeholders for UCSBOrganization pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/71"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization-FrontEnd","number":70,"title":"Table Component for UCSBOrganization plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/70"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization-Form","number":68,"title":"Form Component for UCSBOrganization plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-3/pull/68"}]
